# Generated by Django 5.0.1 on 2025-07-31 19:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('country', models.CharField(max_length=100, verbose_name='Kraj')),
            ],
            options={
                'verbose_name': 'Destynacja',
                'verbose_name_plural': 'Destynacje',
            },
        ),
        migrations.CreateModel(
            name='TravelAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('website', models.URLField(verbose_name='Strona internetowa')),
            ],
            options={
                'verbose_name': 'Biuro podróży',
                'verbose_name_plural': 'Biura podróży',
            },
        ),
        migrations.CreateModel(
            name='TravelOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200, verbose_name='Nazwa hotelu')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('departure_date', models.DateField(verbose_name='Data wylotu')),
                ('return_date', models.DateField(verbose_name='Data powrotu')),
                ('departure_city', models.CharField(max_length=100, verbose_name='Miasto wylotu')),
                ('duration', models.PositiveIntegerField(verbose_name='Długość pobytu (dni)')),
                ('meal_plan', models.CharField(max_length=100, verbose_name='Wyżywienie')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Darmowe WiFi')),
                ('has_sunbeds', models.BooleanField(default=False, verbose_name='Darmowe leżaki')),
                ('offer_url', models.URLField(verbose_name='Link do oferty')),
                ('scrape_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data pobrania')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.travelagency', verbose_name='Biuro podróży')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.destination', verbose_name='Destynacja')),
            ],
            options={
                'verbose_name': 'Oferta turystyczna',
                'verbose_name_plural': 'Oferty turystyczne',
                'ordering': ['-scrape_date', 'price'],
            },
        ),
    ]
